import type { BuildingType, Stage } from '@/data/types';
import type { PhotoKey } from '@/theme/photos';

export interface KBEntry {
  id: string; stages: Stage[]; types: BuildingType[]; keywords: string[];
  lead: string; body: string; source: string; keyPhrase: string;
  requestTitle: string; requestSummary: string;
  recommend: { expertType: string; count: number; fromPrice: number; avatars: PhotoKey[] };
}
const ALL: BuildingType[] = ['villa', 'shop', 'tower', 'factory', 'reno'];
const AV: PhotoKey[] = ['karim', 'lina', 'rashid'];

export const KB: KBEntry[] = [
  { id: 'soil-test', stages: [1, 2], types: ALL, keywords: ['soil', 'geotechnical', 'geotech', 'ground investigation', 'borehole'],
    lead: 'Yes.', body: "A soil test is needed before your {type}'s structure is designed. It decides the foundation.",
    source: 'Project Pulse Villa Guide', keyPhrase: 'soil test', requestTitle: 'Soil test report',
    requestSummary: 'Soil investigation and geotechnical report for a 5-bedroom villa on Al Reem Island, needed before structural design.',
    recommend: { expertType: 'Geotechnical engineer', count: 14, fromPrice: 1800, avatars: AV } },
  { id: 'bid-review', stages: [3, 4], types: ALL, keywords: ['bid', 'bids', 'tender', 'contractor bids', 'compare quotes'],
    lead: 'Yes.', body: 'An independent cost engineer can compare your contractor bids line by line and spot missing scope before you sign.',
    source: 'Project Pulse Tender Guide', keyPhrase: 'bids', requestTitle: 'Bid review',
    requestSummary: 'Review of 3 contractor bids for a 5-bedroom villa on Al Reem Island, with a site visit.',
    recommend: { expertType: 'Cost engineer', count: 9, fromPrice: 2200, avatars: ['omar', 'lina', 'rashid'] } },
  { id: 'boq', stages: [3], types: ALL, keywords: ['boq', 'bill of quantities', 'quantities'],
    lead: 'Good idea.', body: 'A cost engineer checks your bill of quantities against the drawings so bids are priced on the same scope.',
    source: 'Project Pulse Tender Guide', keyPhrase: 'bill of quantities', requestTitle: 'BOQ cost check',
    requestSummary: 'Check of the bill of quantities against the latest drawings before tender.',
    recommend: { expertType: 'Cost engineer', count: 9, fromPrice: 1500, avatars: ['omar', 'rashid', 'lina'] } },
  { id: 'budget', stages: [1], types: ALL, keywords: ['budget', 'afford', 'feasibility', 'how much'],
    lead: 'Start with a feasibility check.', body: 'A cost engineer turns your brief into a realistic budget range using Project Pulse baseline costs.',
    source: 'Project Pulse Planning Guide', keyPhrase: 'budget', requestTitle: 'Budget feasibility',
    requestSummary: 'Feasibility check and budget range for a new villa on Al Reem Island.',
    recommend: { expertType: 'Cost engineer', count: 9, fromPrice: 1500, avatars: ['omar', 'rashid', 'lina'] } },
  { id: 'plot', stages: [1], types: ALL, keywords: ['plot', 'land', 'site survey', 'survey'],
    lead: 'Survey the plot first.', body: 'A topographic survey fixes levels and boundaries so your architect designs to the real site.',
    source: 'Project Pulse Planning Guide', keyPhrase: 'plot', requestTitle: 'Plot survey',
    requestSummary: 'Topographic survey of the plot at Al Reem Island before design starts.',
    recommend: { expertType: 'Civil engineer', count: 11, fromPrice: 1600, avatars: AV } },
  { id: 'permit', stages: [2], types: ALL, keywords: ['permit', 'permits', 'approval', 'municipality', 'building permit'],
    lead: 'Your architect leads this.', body: 'The permit application is prepared from your approved drawings and submitted by a licensed consultant.',
    source: 'Project Pulse Design Guide', keyPhrase: 'permit', requestTitle: 'Permit drawings',
    requestSummary: 'Preparation of permit drawings and submission support for a villa on Al Reem Island.',
    recommend: { expertType: 'Architect', count: 12, fromPrice: 2800, avatars: ['karim', 'nadia', 'lina'] } },
  { id: 'design-review', stages: [2], types: ALL, keywords: ['design', 'drawings', 'second opinion', 'design review', 'layout'],
    lead: 'A second opinion helps.', body: 'An independent architect can review your drawings for buildability and cost before they go to tender.',
    source: 'Project Pulse Design Guide', keyPhrase: 'drawings', requestTitle: 'Design review',
    requestSummary: 'Independent review of concept drawings for buildability and cost.',
    recommend: { expertType: 'Architect', count: 12, fromPrice: 2800, avatars: ['karim', 'nadia', 'lina'] } },
  { id: 'mep', stages: [2, 5], types: ALL, keywords: ['mep', 'electrical', 'plumbing', 'hvac', 'ac', 'air conditioning'],
    lead: 'Check it early.', body: 'An MEP engineer reviews power, cooling and water design so services fit the structure and ceilings.',
    source: 'Project Pulse MEP Guide', keyPhrase: 'MEP', requestTitle: 'MEP design review',
    requestSummary: 'Review of MEP drawings (power, cooling, water) for a villa on Al Reem Island.',
    recommend: { expertType: 'MEP engineer', count: 8, fromPrice: 1600, avatars: ['maya', 'lina', 'rashid'] } },
  { id: 'contractor-choice', stages: [3, 4], types: ALL, keywords: ['choose contractor', 'which contractor', 'contractor', 'builder'],
    lead: 'Compare more than price.', body: 'Check scope, programme and past work. A cost engineer can score the bids for you.',
    source: 'Project Pulse Tender Guide', keyPhrase: 'contractor', requestTitle: 'Bid review',
    requestSummary: 'Scoring of contractor bids on price, scope and programme.',
    recommend: { expertType: 'Cost engineer', count: 9, fromPrice: 2200, avatars: ['omar', 'lina', 'rashid'] } },
  { id: 'contract', stages: [4], types: ALL, keywords: ['contract', 'sign', 'signing', 'agreement'],
    lead: 'Use a standard form.', body: 'Project Pulse recommends its standard contract template, reviewed with your project manager before signing.',
    source: 'Project Pulse Contract Templates', keyPhrase: 'contract', requestTitle: 'Contract review',
    requestSummary: 'Project manager review of the construction contract before signing.',
    recommend: { expertType: 'Project manager', count: 6, fromPrice: 3500, avatars: ['rashid', 'omar', 'lina'] } },
  { id: 'schedule', stages: [4, 5], types: ALL, keywords: ['schedule', 'programme', 'program', 'timeline', 'how long', 'delay', 'delays'],
    lead: 'Follow your baseline schedule.', body: 'Your project manager tracks progress against the Project Pulse baseline schedule and flags slippage early.',
    source: 'Project Pulse Baseline Schedules', keyPhrase: 'schedule', requestTitle: 'Programme check',
    requestSummary: 'Check of the contractor programme against the baseline schedule.',
    recommend: { expertType: 'Project manager', count: 6, fromPrice: 3500, avatars: ['rashid', 'omar', 'lina'] } },
  { id: 'site-visit', stages: [5], types: ALL, keywords: ['site visit', 'inspection', 'inspect', 'quality', 'check the work'],
    lead: 'Yes, regular visits help.', body: 'An engineer inspects the work at key stages and reports with photos, so issues are fixed before they are covered up.',
    source: 'Project Pulse Construction Guide', keyPhrase: 'site visit', requestTitle: 'Site inspection',
    requestSummary: 'Stage inspection of works in progress with a photo report.',
    recommend: { expertType: 'Project manager', count: 6, fromPrice: 2400, avatars: ['rashid', 'omar', 'maya'] } },
  { id: 'concrete', stages: [5], types: ALL, keywords: ['concrete', 'pour', 'rebar', 'reinforcement', 'foundation'],
    lead: 'Inspect before the pour.', body: 'Reinforcement should be checked against the drawings before concrete is poured.',
    source: 'Project Pulse Construction Specifications', keyPhrase: 'pour', requestTitle: 'Pre-pour inspection',
    requestSummary: 'Reinforcement inspection before the concrete pour.',
    recommend: { expertType: 'Structural engineer', count: 7, fromPrice: 1800, avatars: ['lina', 'rashid', 'karim'] } },
  { id: 'waterproofing', stages: [5], types: ALL, keywords: ['waterproofing', 'leak', 'leaks', 'damp', 'roof'],
    lead: 'Test it before finishes.', body: 'Waterproofing is flood-tested before tiles go down. An engineer can witness the test.',
    source: 'Project Pulse Construction Specifications', keyPhrase: 'waterproofing', requestTitle: 'Waterproofing test',
    requestSummary: 'Witnessing of the waterproofing flood test before finishes.',
    recommend: { expertType: 'Project manager', count: 6, fromPrice: 2400, avatars: ['rashid', 'maya', 'omar'] } },
  { id: 'payments', stages: [5], types: ALL, keywords: ['payment', 'invoice', 'valuation', 'pay the contractor'],
    lead: 'Pay against progress.', body: 'Contractor payments should follow certified progress valuations from your cost engineer.',
    source: 'Project Pulse Advisory Articles', keyPhrase: 'payments', requestTitle: 'Progress valuation',
    requestSummary: 'Certification of the contractor progress valuation.',
    recommend: { expertType: 'Cost engineer', count: 9, fromPrice: 2200, avatars: ['omar', 'rashid', 'lina'] } },
  { id: 'snagging', stages: [6], types: ALL, keywords: ['snagging', 'snag', 'defects', 'handover', 'finishing'],
    lead: 'Book a snagging inspection.', body: 'An engineer lists every defect before you accept the keys, so the contractor fixes them first.',
    source: 'Project Pulse Handover Checklist', keyPhrase: 'snagging', requestTitle: 'Snagging inspection',
    requestSummary: 'Snagging inspection before handover with a full defects list.',
    recommend: { expertType: 'Project manager', count: 6, fromPrice: 2400, avatars: ['rashid', 'maya', 'omar'] } },
  { id: 'handover-docs', stages: [6], types: ALL, keywords: ['documents', 'warranty', 'warranties', 'as built', 'manuals'],
    lead: 'Collect them at handover.', body: 'Ask for as-built drawings, warranties and equipment manuals before the final payment.',
    source: 'Project Pulse Handover Checklist', keyPhrase: 'handover documents', requestTitle: 'Handover documents check',
    requestSummary: 'Check that all handover documents and warranties are complete.',
    recommend: { expertType: 'Project manager', count: 6, fromPrice: 2400, avatars: ['rashid', 'omar', 'maya'] } },
  { id: 'interior', stages: [2, 5, 6], types: ALL, keywords: ['interior', 'interiors', 'finishes', 'furniture', 'kitchen design', 'tiles'],
    lead: 'Plan finishes early.', body: 'An interior designer can set finishes and a budget before the contractor orders materials.',
    source: 'Project Pulse Advisory Articles', keyPhrase: 'finishes', requestTitle: 'Interior concept',
    requestSummary: 'Interior concept and finishes schedule for a villa on Al Reem Island.',
    recommend: { expertType: 'Interior designer', count: 10, fromPrice: 2500, avatars: ['nadia', 'karim', 'lina'] } },
  { id: 'value-engineering', stages: [2, 3], types: ALL, keywords: ['save money', 'cheaper', 'reduce cost', 'value engineering', 'over budget'],
    lead: 'Value engineering can help.', body: 'A cost engineer suggests equivalent specifications that cost less without changing the design intent.',
    source: 'Project Pulse Advisory Articles', keyPhrase: 'reduce cost', requestTitle: 'Value engineering review',
    requestSummary: 'Value engineering review to bring the project back within budget.',
    recommend: { expertType: 'Cost engineer', count: 9, fromPrice: 2200, avatars: ['omar', 'lina', 'rashid'] } },
  { id: 'shop-fitout', stages: [2, 5], types: ['shop'], keywords: ['fit out', 'fitout', 'fit-out', 'storefront', 'retail'],
    lead: 'Check landlord rules first.', body: 'Retail fit-outs follow the landlord design guide. An architect aligns your design before works start.',
    source: 'Project Pulse Retail Guide', keyPhrase: 'fit-out', requestTitle: 'Fit-out design check',
    requestSummary: 'Design check of the retail fit-out against the landlord guide.',
    recommend: { expertType: 'Architect', count: 12, fromPrice: 2800, avatars: ['karim', 'nadia', 'lina'] } },
];
