// ids = file names in design/approved/ (a plain array literal: tools/fidelity/capture.mjs reads this file)
export const GALLERY = [
  { id: '01-splash', label: 'Splash', href: '/?stay=1' }, { id: '02-welcome-role', label: 'Welcome', href: '/onboarding/welcome' },
  { id: '03-sign-up', label: 'Sign in', href: '/onboarding/signup' }, { id: '04-building-type', label: 'What are you building?', href: '/onboarding/building' },
  { id: '04b-building-chosen', label: 'Building chosen', href: '/onboarding/chosen?stay=1' }, { id: '05-stage', label: 'Stage', href: '/onboarding/stage?stage=5' },
  { id: '06-building-your-project', label: 'Building your project', href: '/onboarding/creating?stay=1' },
  { id: '08-home', label: 'Home', href: '/home' }, { id: '09-pulse-opening', label: 'Pulse opening', href: '/pulse' },
  { id: '09a-ask', label: 'Pulse · Ask', href: '/pulse?state=ask' },
  { id: '09b-thinking', label: 'Pulse · Thinking', href: '/pulse?state=thinking&stay=1&q=Do%20I%20need%20a%20soil%20test%3F' },
  { id: '09c-answer', label: 'Pulse · Answer', href: '/pulse?state=answer&q=Do%20I%20need%20a%20soil%20test%3F' },
  { id: '09d-flagged', label: 'Pulse · Flagged', href: '/pulse?state=flagged&q=Can%20I%20remove%20the%20kitchen%20wall%3F' },
  { id: '10-request-quote', label: 'Request a quote', href: '/request?kb=soil-test' }, { id: '10b-sent', label: 'Sent', href: '/request/sent' },
  { id: '11-experts', label: 'Experts', href: '/experts' }, { id: '12-expert-profile', label: 'Expert profile', href: '/expert/omar' },
  { id: '13-quotes', label: 'Quotes', href: '/quotes?request=req-bid' },
  { id: '14a-pick-time', label: 'Pick a time', href: '/book?expert=omar&service=bid-visit' },
  { id: '14b-payment', label: 'Payment', href: '/book?expert=omar&service=bid-visit&pay=1' }, { id: '14c-booked', label: 'Booked', href: '/book/done' },
  { id: '15-job-tracking', label: 'Job tracking', href: '/job/job-1' }, { id: '15b-report', label: 'Report ready', href: '/report/job-1' },
  { id: '16-review', label: 'Review', href: '/review/job-1' }, { id: '17-project-milestones', label: 'Project · Milestones', href: '/project' },
  { id: '17b-budget', label: 'Project · Budget', href: '/project?tab=budget' }, { id: '17c-site', label: 'Project · Site', href: '/project?tab=site' },
  { id: '18-inbox', label: 'Inbox', href: '/inbox' }, { id: '18b-chat', label: 'Chat', href: '/chat/omar' },
  { id: '19-updates', label: 'Updates', href: '/inbox?tab=updates' }, { id: '20-profile', label: 'Profile', href: '/profile' },
  { id: 'E1-role', label: 'Expert · Role', href: '/expert-role' }, { id: 'E2-profile-setup', label: 'Expert · Profile', href: '/expert-setup' },
  { id: 'E3-verified', label: 'Expert · Verified', href: '/expert-verified?stay=1' }, { id: 'E4-dashboard', label: 'Expert · Dashboard', href: '/pro' },
  { id: 'E5-send-quote', label: 'Expert · Send quote', href: '/pro/request/req-soil' }, { id: 'E6-availability', label: 'Expert · Availability', href: '/pro/jobs' },
  { id: 'E7-deliverables', label: 'Expert · Deliverables', href: '/pro/job/job-1' }, { id: 'E8-earnings', label: 'Expert · Earnings', href: '/pro/earnings' },
];
